sudo: false

language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "1"
  - "0.12"
  - "0.11"
  - "0.10"

cache:
  directories:
  - node_modules

notifications:
  email: false

before_script:
- npm prune

script:
  - npm test
  - npm run coverage
